[package]
name = "halo2-aggregation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-base = "0.4.1"
halo2-ecc = "0.4.1"
halo2curves = "0.6.0"
rand_core = "0.6.4"
serde_json = "1.0.111"
